version: '3.8'
services:

  #PHP Service
  php:
    container_name: php-8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/wirelessLogic
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - Logic-network

  #Nginx Service
  nginx:
    container_name: nginx-alpine
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/wirelessLogic
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - Logic-network

#Docker Networks
networks:
  Logic-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local